import sys
import requests

class SentimentAPI:
    '''
        This program uses ParallelDots for all text analysis (https://www.paralleldots.com)
    '''
    url = "https://apis.paralleldots.com/v3/"
    headers = {'Content-Type': 'application/x-www-form-urlencoded'}
    api_key = "apikey"

    def __init__(self,apiExtension):
        self.url = "{}{}".format(self.url, apiExtension)


def main():
    print("hello world")


def make_sentiment_request(text, api_key):
    '''
        {
            "probabilities": {
                "positive": 0.241,
                "neutral": 0.304,
                "negative": 0.454
            },
            "usage": "By accessing ParallelDots API or using information generated by ParallelDots API, you are agreeing to be bound by the ParallelDots API Terms of Use: http://www.paralleldots.com/terms-and-conditions",
            "sentiment": "negative"
        }
    '''
    api_object = SentimentAPI("sentiment")
    payload = "text={}&api_key={}&lang_code=en".format(text, api_object.api_key)
    response = requests.request("POST", api_object.url, data=payload, headers=api_object.headers)

    print(response.text)


def make_emotion_request(text, api_key):
    '''
    {
        "emotion": { 
            "probabilities": {
                "angry": 0.376,
                "indifferent": 0.189,
                "sad": 0.381,
                "excited": 0.014,
                "happy": 0.04 },
                "emotion": "sad" 
            },
            "usage": "By accessing ParallelDots API or using information generated by ParallelDots API, you are agreeing to be bound by the ParallelDots API Terms of Use: http://www.paralleldots.com/terms-and-conditions"
        } 
    '''
    api_object = SentimentAPI("emotion")
    payload = "text={}&api_key={}&lang_code=en".format(text, api_object.api_key)
    response = requests.request("POST", api_object.url, data=payload, headers=api_object.headers)

    print(response.text)


if __name__ == '__main__':
    main()